Renommer l'id du connecteur QFDMO_DJANGO_DB
incubateur-ademe/quefairedemesobjets pull request #1015
Opened 2024-11-12 15:34 UTC by kolok

# Description succincte du problème résolu

L'identifiant de connection contenait des '-', cela ne permettait pas de définir ce connecteur en utilisant les variables d'environnement sur certains sstème car ce caractère n'était pas autorisé.
Dans cette PR, on renomme donc l'identifiant de connection en utilisant des '_' en lieu et place des '-'

**Type de changement** :

- [x] Bug fix
- [ ] Nouvelle fonctionnalité
- [ ] Mise à jour de données / DAG
- [ ] Les changements nécessitent une mise à jour de documentation
- [ ] Refactoring de code (explication à retrouver dans la description)

## Auto-review

Les trucs à faire avant de demander une review :

- [ ] J'ai bien relu mon code
- [ ] La CI passe bien
- [ ] En cas d'ajout de variable d'environnement, j'ai bien mis à jour le `.env.template`
- [ ] J'ai ajouté des tests qui couvrent le nouveau code

## Comment tester

En local / staging :
- …

2024-11-12 18:11 UTC, fabienheureux requested changes
Tant qu'à faire on en ferait pas une constante quelque part ?

2024-11-13 07:19 UTC, fabienheureux commented
Voire même un truc comme 

```py
from airflow.providers.postgres.hooks.postgres import PostgresHook

class DefaultPostgresHook(PostgresHook):
    def __init__(self, postgres_conn_id: str = 'qfdmo_django_db', *args, **kwargs):
        super().__init__(postgres_conn_id=postgres_conn_id, *args, **kwargs)
```

qu'on importe ensuite ?

2024-11-13 10:09 UTC, kolok commented
> Voire même un truc comme
> 
> ```python
> from airflow.providers.postgres.hooks.postgres import PostgresHook
> 
> class DefaultPostgresHook(PostgresHook):
>     def __init__(self, postgres_conn_id: str = 'qfdmo_django_db', *args, **kwargs):
>         super().__init__(postgres_conn_id=postgres_conn_id, *args, **kwargs)
> ```
> 
> qu'on importe ensuite ?

Je te propose de garder ça pour la prochaine fois, Max est en train de refacto à fond, c'et peut-être déjà dans sa PR ou dans sa tête

2024-11-13 10:31 UTC, fabienheureux commented
En effet

2024-11-13 10:31 UTC, fabienheureux approved these changes
OK pour moi (cf refacto en cours de Max)

2024-11-13 14:38 UTC, closed without merging