Ajout de la noton de SIREN
incubateur-ademe/quefairedemesobjets pull request #1105
Opened 2024-12-03 21:43 UTC by kolok

# Description succincte du problème résolu

Carte Notion : [Importer les données EMPAP / OCAPEM / Citeo](https://www.notion.so/accelerateur-transition-ecologique-ademe/Importer-les-donn-es-EMPAP-OCAPEM-Citeo-1306523d57d7804c9e0cd1a52b19269f?pvs=4)

CITEO fournit les siren et pas les siret, on ajout sonc un colonne siren et cette notion un peu partout

**Type de changement** :

- [ ] Bug fix
- [ ] Nouvelle fonctionnalité
- [ ] Mise à jour de données / DAG
- [ ] Les changements nécessitent une mise à jour de documentation
- [ ] Refactoring de code (explication à retrouver dans la description)

## Auto-review

Les trucs à faire avant de demander une review :

- [ ] J'ai bien relu mon code
- [ ] La CI passe bien
- [ ] En cas d'ajout de variable d'environnement, j'ai bien mis à jour le `.env.template`
- [ ] J'ai ajouté des tests qui couvrent le nouveau code

## Comment tester

En local / staging :
- …

2024-12-05 08:12 UTC, maxcorbeau commented on dags/sources/tasks/transform/transform_column.py
> +    return ""
merci de retourner `None`, voir: [Qualité de données: interdire les vides autre que NULL/NONE](https://www.notion.so/accelerateur-transition-ecologique-ademe/Qualit-de-donn-es-interdire-les-vides-autre-que-NULL-NONE-1436523d57d780b090afe8e4e0be4608?pvs=4)

2024-12-05 08:12 UTC, maxcorbeau commented on dags/sources/tasks/transform/transform_column.py
> +    return ""
merci de retourner None, voir: [Qualité de données: interdire les vides autre que NULL/NONE](https://www.notion.so/accelerateur-transition-ecologique-ademe/Qualit-de-donn-es-interdire-les-vides-autre-que-NULL-NONE-1436523d57d780b090afe8e4e0be4608?pvs=4)

2024-12-05 08:13 UTC, maxcorbeau requested changes
merci de retourner `None` et pas `""` en cas d'invalidité, voir: [Qualité de données: interdire les vides autre que NULL/NONE](https://www.notion.so/accelerateur-transition-ecologique-ademe/Qualit-de-donn-es-interdire-les-vides-autre-que-NULL-NONE-1436523d57d780b090afe8e4e0be4608?pvs=4)

2024-12-05 08:28 UTC, maxcorbeau commented on dags/sources/tasks/transform/transform_column.py
> +    return ""
Et le cas de figure où SIRET est valide (14 chiffres) et on prend les 9 premiers chiffres comme SIREN?

2024-12-05 09:48 UTC, kolok commented on dags/sources/tasks/transform/transform_column.py
> +    return ""
J'ai mis le sujet siren depuis le siren dans **Amélioration possible** dans les commentaires
Je te propose de faire une autre PR là dessus pour une meilleur visibilité

2024-12-05 10:09 UTC, kolok commented on dags/sources/tasks/transform/transform_column.py
> +    return ""
Pour les chaines de caractère j'avais eu un retour de sonarcube (application des règles ) sur un autre projet qui préconisait de ne pas permettre les valeurs null pour les chaines de caractère en base de donnée car après tu ne sais plus quelle est la valeur par defaut "" ou Null

J'ai du mal à retrouver la référence à cette "policy"

Cependant, pour le moment on n'utilise pas sonarcube et la valeur null est autorisée en DB

2024-12-05 14:25 UTC, maxcorbeau approved these changes

2024-12-05 14:25 UTC, merged

2024-12-11 08:22 UTC, maxcorbeau commented on dags/sources/tasks/transform/transform_column.py
> +    if len(siret) == 9:
j'ai laissé passé ça... Un SIRET a 14 chiffres