:arrow_down:  Source SCRELEC v1
incubateur-ademe/quefairedemesobjets pull request #1115
Opened 2024-12-09 15:35 UTC by maxcorbeau

# :arrow_down:  Source SCRELEC v1

Carte Notion : [Importer source SCRELEC PA=“Piles et Accumulateurs” (v1)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Importer-source-SCRELEC-PA-Piles-et-Accumulateurs-v1-1526523d57d780b49c85cd79d6baac61)

 - **quoi**: nouveau `DAG` pour la nouvelle source SCRELEC
   - **bonus**: `scripts/source_data_audit.py` qui télécharge la donnée d'une source et utilise https://docs.profiling.ydata.ai/latest/ + quelques règles métier pour nous aider à explorer la donnée (et gagner du temps sur la création du `DAG`)
 - **pourquoi**: on veut ingérer la nouvelle source
 - **comment**: standard éco-organisme, quelques changements (voir ci-dessous)

## :warning: Changements  

 - `mapping_utils.transform_acteur_type_id`: ajout d'un mapping dynamique, voir décision: [:left_right_arrow:  Mapper les codes acteur type source dynamiquement](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mapper-les-codes-acteur-type-source-dynamiquement-1576523d57d7803b9a98c146730088c5?pvs=4)
 - `source_data_normalize`: ajout de la validation `siren/siret` en dure
 - `source_data_validate`: rejet si problèmes de `siren/siret`

## :black_square_button:  A faire avant merge

- [ ] `mapping_utils.transform_acteur_type_id`: étendre les tests unitaires

## :bulb:  A propos du script d'audit

`scripts/source_data_audit.py` permet de gagner du temps dans la création du `DAG` en explorant la donnée au préalable pour anticiper/prévenir des potentiels problèmes.

### Exemple: un résumé des champs pour le mapping

![image](https://github.com/user-attachments/assets/d15d3a95-f3af-49ae-b5ad-be350abe0cc9)

### Exemple: problèmes de données

On peut voir qu'on a des problèmes sur le `siret`

![image](https://github.com/user-attachments/assets/905ddcb5-f77b-415c-8277-9a55ae89e5dc)

2024-12-09 17:44 UTC, kolok requested changes
Comme échanger sur Mattermost, la modification de la gestion du `siret` et du `siren` doit -être isolé dans une autre PR car il peut y avoir des effets de bord important et cette réorganisation ouvre des questions d'architecture logiciel

2024-12-09 17:44 UTC, kolok commented on dags/sources/dags/source_screlec.py
> +            "adresse_format_ban": "adresse_format_ban",
Quand c'est la même origin et destination, il n'y a pas besoin de les re préciser car column_mapping fait des renames

2024-12-09 17:44 UTC, kolok commented on dags/sources/tasks/business_logic/source_data_validate.py
> +
Est-ce que ça casse l'injestion quand une des valeurs est vide ?

Si oui, c'est trop restrictif

2024-12-09 17:44 UTC, kolok commented on dags/sources/dags/source_screlec.py
> +            "accessible": None,
Si l'objectif est de supprimer ces colonnes, alors il faut les mettre dans le paramètre `column_to_drop`

Là il ne se passe rien pour ces colonnes :

cf.
```
    # Renommage des colonnes
    df = df.rename(columns={k: v for k, v in column_mapping.items() if v is not None})
```

2024-12-09 17:44 UTC, kolok commented on scripts/source_data_audit.py
je ne sais pas comment on pourrait faire mais ce DAG n'a pas vocation à être déployé en prod

2024-12-09 18:03 UTC, kolok commented on dags/utils/mapping_utils.py
Quit à modifier drastiquement cette fonction, autant la déplacer dans transformation_column.py et y ajouter un ensemble de tests pour

2024-12-10 11:01 UTC, fabienheureux commented on dags/sources/config/airflow_params.py
> +URL_NOMENCLARURE_DECHET = (
```suggestion
URL_NOMENCLATURE_DECHET = (
```

2024-12-16 06:19 UTC, maxcorbeau commented on dags/sources/dags/source_screlec.py
> +            "adresse_format_ban": "adresse_format_ban",
N'est-ce pas mieux de garder le mapping pour expliciter ce que l'on obtient en terme de colonnes de la source?

2024-12-16 06:24 UTC, maxcorbeau commented on dags/sources/tasks/business_logic/source_data_validate.py
> +
Valeurs vides sont permises, je vais formaliser avec une décision technique ce qu'on attends de l'étape de validation, à savoir:
 - **autoriser les valeurs nulles (dans certains cas)**: au motif que l'absence de données n'est pas forcément de la mauvaise donnée:
   - **exemple de cas autorisés**: siret / siren
   - **exemple de cas non-autorisés**: public accueilli, puisqu'on a une règle métier qui requiert savoir si le public est particulier
 - **soulever des exceptions pour les valeurs non-nulles**: si une valeur est non-nulle mais de format incorrect, alors on ne doit pas la laisser passer

2024-12-16 06:24 UTC, maxcorbeau commented on dags/sources/dags/source_screlec.py
> +            "accessible": None,
ok

2024-12-16 06:25 UTC, maxcorbeau commented on scripts/source_data_audit.py
ce n'est pas un `DAG`, juste un script d'audit qui a vocation à rester un script.

2024-12-16 06:30 UTC, maxcorbeau commented on dags/utils/mapping_utils.py
@chrischarousset à finalement décidé d'annuler la décision correspondante ( [↔️ Mapper les codes acteur type source dynamiquement](https://www.notion.so/accelerateur-transition-ecologique-ademe/Mapper-les-codes-acteur-type-source-dynamiquement-1576523d57d7803b9a98c146730088c5?pvs=4), [voir discussion](https://mattermost.incubateur.net/betagouv/pl/a69rapj1ejdp8c3wx8a4nnu3me) ), donc ces changements vont être annulés.

2024-12-16 06:45 UTC, maxcorbeau commented
### :red_circle: Annulée et remplacée par [cette PR](https://github.com/incubateur-ademe/quefairedemesobjets/pull/1138) :red_circle:

2024-12-16 06:46 UTC, closed without merging