:arrow_down:  Source SCRELEC v2
incubateur-ademe/quefairedemesobjets pull request #1138
Opened 2024-12-16 06:44 UTC by maxcorbeau

# :arrow_down:  Source SCRELEC v2

Annule et remplace [cette PR](https://github.com/incubateur-ademe/quefairedemesobjets/pull/1115)

Carte Notion : [Importer source SCRELEC PA=“Piles et Accumulateurs”](https://www.notion.so/accelerateur-transition-ecologique-ademe/Importer-source-SCRELEC-PA-Piles-et-Accumulateurs-v1-1526523d57d780b49c85cd79d6baac61)

 - **quoi**: nouveau `DAG` pour la nouvelle source SCRELEC
   - **bonus**: `scripts/source_data_audit.py` qui télécharge la donnée d'une source et utilise https://docs.profiling.ydata.ai/latest/ + quelques règles métier pour nous aider à explorer la donnée (et gagner du temps sur la création du `DAG`)
 - **pourquoi**: on veut ingérer la nouvelle source
 - **comment**: standard éco-organisme, **0 changements**

## :bulb:  A propos du script d'audit

`scripts/source_data_audit.py` permet de gagner du temps dans la création du `DAG` en explorant la donnée au préalable pour anticiper/prévenir des potentiels problèmes.

### Exemple: un résumé des champs pour le mapping

![image](https://github.com/user-attachments/assets/d15d3a95-f3af-49ae-b5ad-be350abe0cc9)

### Exemple: problèmes de données

On peut voir qu'on a des problèmes sur le `siret`

![image](https://github.com/user-attachments/assets/905ddcb5-f77b-415c-8277-9a55ae89e5dc)

2024-12-16 07:27 UTC, kolok requested changes

2024-12-16 07:27 UTC, kolok commented on dags/sources/dags/source_screlec.py
> +            "siret": "siret",
ici on doit mettre la fonction de transformation qui cleanup les sirets (comme elle existe et est exécutée sur les autres source eco-orgnisme)

2024-12-16 07:27 UTC, kolok commented on dags/sources/dags/source_screlec.py
> +            COL_POINT_COLLECTE: COL_POINT_COLLECTE,
Je ne voit pas l'intérêt de ces constantes

2024-12-16 07:27 UTC, kolok commented on dags/sources/dags/source_screlec.py
> +            "adresse_format_ban": "adresse_format_ban",
Pas nécessaire de déclarer les champs qui ont la même orgin et destination car c'est un rename colonne (comme c'est fait aujourd'hui dans les autres source eco-organisme)

ça pourra changer plus tard mais ce sera dans une autre PR

2024-12-16 09:16 UTC, maxcorbeau commented on dags/sources/dags/source_screlec.py
> +            COL_POINT_COLLECTE: COL_POINT_COLLECTE,
j'ai mis un commentaire en haut de fichier: c'est parce que j'ai des conflits entre VSCode et le pre-commit où chacun change d'avis sur la longueur des lignes et je me retrouver coincé en boucle à ne pas pouvoir pousser. D'où le `FIX ME` pour résoudre ce problème, pas en lien direct avec cette PR, à une date ultérieure.

2024-12-16 09:21 UTC, maxcorbeau commented on dags/sources/dags/source_screlec.py
> +            "siret": "siret",
ok, fait dans le nouveau commit

2024-12-16 11:28 UTC, kolok commented on dags/sources/dags/source_screlec.py
> +            "adresse_format_ban": "adresse_format_ban",
Je te propose qu'on fasse ça dans une autre PR, peut-être un petit différemment à discuter, j'aimerai qu'on simplie les paramètres du DAG, d'où des propositions de PR draft :

- #1128
- #1117

Pour cette PR, je préfère qu'on n'ait pas ces colonnes pour garder la cohérence avec la config des autres sources.

En plus, cela résolvera ton pb de nom de colonne trop long ci-dessus

2024-12-17 08:05 UTC, kolok approved these changes

2024-12-17 08:27 UTC, merged