Added (obligatoire) in the forms label for the mandatory form field
incubateur-ademe/quefairedemesobjets pull request #637
Opened 2024-06-17 12:47 UTC by LuluFreeDesign

2024-06-18 16:00 UTC, kolok requested changes

2024-06-18 16:00 UTC, kolok commented on qfdmo/forms.py
> +        label="Indiquer un objet (obligatoire)",
Nope, On ne peut pas le faire ici car cela va apparaitre dans les filtres de "La carte" comme obligatoire alors que ça ne l'ai pas

2024-06-18 16:00 UTC, kolok commented on qfdmo/forms.py
> +        label="Indiquer un objet (obligatoire)",
Je le ferai @LuluFreeDesign

2024-06-19 08:04 UTC, LuluFreeDesign commented on qfdmo/forms.py
> +        label="Indiquer un objet (obligatoire)",
Oki ! merci Nico, je close la PR

2024-06-19 08:04 UTC, closed without merging