Add Axe to Playwright tests
incubateur-ademe/quefairedemesobjets pull request #671
Opened 2024-06-27 19:49 UTC by fabienheureux

Add e2e tests for accessibility

2024-06-28 12:32 UTC, kolok requested changes
cool !!!
Mais du coup, il va falloir qu'on corrige l'erreur : `iFrame is WCAG compliant` avant de merger ça :)

2024-06-28 12:32 UTC, kolok commented on .github/workflows/push_pr.yml
> +  workflow_dispatch:
ça pourrait faire l'objet d'une autre PR

2024-06-28 12:38 UTC, fabienheureux commented
Oui 😬😬😬

2024-06-28 12:39 UTC, fabienheureux commented on .github/workflows/push_pr.yml
> +  workflow_dispatch:
En effet c'était pour mes tests je pensais pas forcément le merger

2024-07-22 09:56 UTC, fabienheureux commented
Fermée au profit de #708

2024-07-22 09:56 UTC, closed without merging