A11y feedbacks lucas batch 2
incubateur-ademe/quefairedemesobjets pull request #807
Opened 2024-08-21 14:55 UTC by fabienheureux

# Description succincte du problème résolu

Carte Notion : [Titre de la carte](https://notion.so/...)

Description plus détaillée de l'intention, l'approche ou de l'implémentation (ce qui n’est pas visible directement en lisant le code)

**Type de changement** :
- [ ] Bug fix
- [ ] Nouvelle fonctionnalité
- [ ] Mise à jour de données / DAG
- [ ] Les changements nécessitent une mise à jour de documentation
- [ ] Refactoring de code (explication à retrouver dans la description)

## Auto-review

Les trucs à faire avant de demander une review :
- [ ] J'ai bien relu mon code
- [ ] La CI passe bien
- [ ] En cas d'ajout de variable d'environnement, j'ai bien mis à jour le `.env.template`
- [ ] J'ai ajouté des tests qui couvrent le nouveau code

## Comment tester

En local / staging :
- Récupérer la base de production
- Aller sur http://localhost:8000
- Cliquer sur ABC
- …

## Développement local

- Mettre à jour le `.env`
- Réinstaller les dépendances Python avec `pip install -r requirements.txt -r dev-requirements.txt`
- Réinstaller les dépendances node avec `npm install`
- Rebuild la stack docker avec `docker compose build`
- ...

## Déploiement

- Exécuter les migrations
- Exécuter la commande `rf -rf /`
- ...

2024-08-22 14:30 UTC, fabienheureux commented on dags/create_final_actors.py
> +                "action_principale_id",
Je sais pas d'où ça sort ça, à ne pas merger

2024-08-22 14:30 UTC, fabienheureux commented on jinja2/layout/footer.html
> +                <a href="/" title="Retour à l’accueil du site - Nom de l’entité (ministère, secrétariat d‘état, gouvernement)" class="fr-footer__brand-link qfdmo-outline-none qfdmo-bg-none">
j'ai été obligé de passer outre l'implémentation du DSFR, à bien tester

2024-08-22 14:31 UTC, fabienheureux commented on jinja2/layout/header.html
> +                                    target="_blank"  rel="noreferrer"
```suggestion
                                    target="_blank" rel="noreferrer"
```

2024-08-22 14:31 UTC, fabienheureux commented on jinja2/qfdmo/_addresses_partials/filters/carte_apropos.html
> +    <div class="qfdmo-bg-white qfdmo-duration-300 qfdmo-invisible" data-search-solution-form-target="aProposFormPanel">
```suggestion
    <div class="qfdmo-bg-white qfdmo-duration-300 qfdmo-h-0 qfdmo-invisible" data-search-solution-form-target="aProposFormPanel">
```

2024-08-22 14:32 UTC, fabienheureux commented on jinja2/qfdmo/_addresses_partials/filters/panel_filters.html
> +<div class='fr-container qfdmo-px-0 qfdmo-absolute qfdmo-inset-0 qfdmo-font-black qfdmo-z-[10010] qfdmo-flex-col qfdmo-hidden'
classe CSS inutilisée

2024-08-22 14:33 UTC, fabienheureux commented on jinja2/qfdmo/adresse/detail.html
> +                                tabindex="-1"
Celui là et suivant permet de palier à une défaut du DSFR lorsqu'on a des liens dans un tooltip, pour la navigation au clavier 

Cf https://mattermost.incubateur.net/betagouv/pl/gcq8yo5ajjbrpxuadq1cy47o1r

2024-08-22 15:11 UTC, fabienheureux commented on templates/django/forms/widgets/autocomplete.html
> +        id="{{ widget.attrs.id }}"
je pense qu'il y a mieux à faire que ça, mais je serais d'avis de se donner une refacto des forms en septembre pour notamment exploiter les renderers django 

https://docs.djangoproject.com/fr/5.1/ref/forms/renderers/

2024-08-27 09:55 UTC, kolok commented
## Pb affichage

Sur Chrome, faire une recherche, puis cliquer sur retour à la recherche. On a un pb d'affichage

![CleanShot 2024-08-27 at 11 52 17@2x](https://github.com/user-attachments/assets/1d126244-5bd4-45f6-ab5e-e5b00f36018e)

2024-08-28 06:25 UTC, kolok commented
On ne peut pas scroller les solutions en ligne

![CleanShot 2024-08-28 at 08 24 08@2x](https://github.com/user-attachments/assets/cc9c4984-e9b5-48ed-a2db-9364282e5e8f)

2024-08-28 09:30 UTC, fabienheureux commented on jinja2/layout/header.html
> +<header class="fr-header">
alors c'est pas w3c-compliant, mais ça ne pose pas de problème outre mesure. 
C'est juste qu'ils sont définis par défaut pour ces éléments à ces valeurs.

J'ai prévu quelques issues DSFR à l'issue de cette PR, notamment les contrôles segmentés qu'il faudrait refactoriser.

2024-08-28 09:36 UTC, fabienheureux commented on templates/django/forms/widgets/autocomplete.html
> +        id="{{ widget.attrs.id }}"
j'ai ouvert une PR dédiée à cette refacto, #818

2024-08-28 20:59 UTC, fabienheureux commented on jinja2/layout/header.html
> +<header class="fr-header">
j'ai complété la PR avec les infos

2024-08-29 13:40 UTC, kolok commented
En mode carte, je ne vois plus la carte :

![CleanShot 2024-08-29 at 15 34 07@2x](https://github.com/user-attachments/assets/8b16d69d-db25-4f83-b7b8-39d82fb3a478)

2024-08-29 18:32 UTC, fabienheureux commented
Bien vu...c'est corrigé. 
Je vais ajouter un test e2e parce que je sens que ça va m'arriver souvent cette histoire

2024-09-02 15:25 UTC, kolok requested changes
Revue avec @fabienheureux 

Un comprtement bloquant : l'impossibilité de scroller sur le formulaire de recherche

2024-09-12 15:35 UTC, fabienheureux commented
@kolok c'est de nouveau dispo en review. 
J'ai testé pas mal de comportement de _ça me semble ok_ mais je veux bien ton regard ! (sur le fonctionnel et pourquoi pas une dernière relecture du code)

2024-09-16 06:30 UTC, kolok commented
J'ai toujours un soucis lorsque l'iframe s'affiche dans un espace restreint (ex: 500px x 500px) il n'est pas possible de cliquer sur le bouton de recherche :

http://localhost:8000/iframe/configurateur?iframe_mode=form&direction=jai&first_dir=first_jecherche&action_displayed=preter&action_displayed=emprunter&action_displayed=louer&action_displayed=mettreenlocation&action_displayed=reparer&action_displayed=donner&action_displayed=acheter&action_displayed=revendre&action_displayed=trier&action_list=reparer&max_width=500px&height=500px&limit=25&address_placeholder=Tape+ton+adresse&iframe_attributes=&bounding_box=%7B+++%22southWest%22%3A%7B%22lat%22%3A48.916%2C%22lng%22%3A2.298202514648438%7D%2C+++%22northEast%22%3A%7B%22lat%22%3A48.98742568330284%2C%22lng%22%3A2.483596801757813%7D+%7D#iframe_view

2024-09-16 06:39 UTC, kolok commented
J'ai du mal à retrouver comment ça marchait avant car on avait la scrollbar sur le formulaire en prod et ça marchait correctement

Maintenant, on n'a plus la scrollbar ni en prod ni dans cette PR. cela pose un problème aussi quand la hauteur par défaut est utilisé dans la nouvelle version car le en cas d'erreur sur les champs, le bonton rechercher n'est plus visible : 

![CleanShot 2024-09-16 at 08 38 59@2x](https://github.com/user-attachments/assets/776aa747-0357-4edb-8801-16895140aa55)

2024-09-16 06:40 UTC, kolok commented
Les tests e2e passe en local sur mon PC, ici il merdouille, je ne sais pas pourquoi

2024-09-16 11:42 UTC, fabienheureux commented
C'est good ils passent !

2024-09-17 06:23 UTC, kolok approved these changes
👍

2024-09-17 06:25 UTC, merged