Les displayedacteurs doivent être modifiables en environnement de dev pour faciliter les tests
incubateur-ademe/quefairedemesobjets pull request #823
Opened 2024-08-26 14:30 UTC by kolok

# Description succincte du problème résolu

Carte Notion : N/A

Rendre modifiable les displayedacteur en environnement de dev permet de tester l'affichage des acteurs plus simplement sans avoir a lancer le DAG de compilation des acteurs

**Type de changement** :
- [ ] Bug fix
- [x] Nouvelle fonctionnalité
- [ ] Mise à jour de données / DAG
- [ ] Les changements nécessitent une mise à jour de documentation
- [ ] Refactoring de code (explication à retrouver dans la description)

## Auto-review

Les trucs à faire avant de demander une review :
- [x] J'ai bien relu mon code
- [x] La CI passe bien
- [ ] En cas d'ajout de variable d'environnement, j'ai bien mis à jour le `.env.template`
- [ ] J'ai ajouté des tests qui couvrent le nouveau code

## Comment tester

En local / staging :
- Editer un displayedacteur en local, ne pas pouvoir l'éditer en preprod et en prod

## Développement local

N/A

## Déploiement

N/A

2024-08-26 19:52 UTC, fabienheureux requested changes
On ne pourrait pas utiliser `settings.DEBUG` plutôt ?

2024-08-26 21:34 UTC, kolok commented
> On ne pourrait pas utiliser `settings.DEBUG` plutôt ?

👍

2024-08-26 21:40 UTC, fabienheureux approved these changes
J'ai mis un commentaire / suggestion 

Rien de bloquant pour autant, ok pour moi

2024-08-26 21:40 UTC, fabienheureux commented on core/context_processors.py
> +        "ENVIRONMENT": settings.ENVIRONMENT,
```suggestion
```

Je pense qu'on en a plus besoin

2024-08-27 09:35 UTC, kolok commented on core/context_processors.py
> +        "ENVIRONMENT": settings.ENVIRONMENT,
On en a encore besoin pour la coloration des admins selon l'environnement :)

2024-08-27 09:36 UTC, merged