Permet à la carte de recalculer ses limites lorsque la largeur du con…
incubateur-ademe/quefairedemesobjets pull request #836
Opened 2024-09-02 16:04 UTC by fabienheureux

…teneur change

# Description succincte du problème résolu

Carte Notion : [Problème au 1er chargement de la carte sur sites intégrés - reproduit suite à MEP](https://www.notion.so/accelerateur-transition-ecologique-ademe/Probl-me-au-chargement-de-la-carte-sur-sites-int-gr-s-retester-suite-MEP-a252d6e3f6cc418fa28347edd9618c1a?pvs=4)

Description plus détaillée de l'intention, l'approche ou de l'implémentation (ce qui n’est pas visible directement en lisant le code)

**Type de changement** :
- [ ] Bug fix
- [ ] Nouvelle fonctionnalité
- [ ] Mise à jour de données / DAG
- [ ] Les changements nécessitent une mise à jour de documentation
- [ ] Refactoring de code (explication à retrouver dans la description)

## Auto-review

Les trucs à faire avant de demander une review :
- [ ] J'ai bien relu mon code
- [ ] La CI passe bien
- [ ] En cas d'ajout de variable d'environnement, j'ai bien mis à jour le `.env.template`
- [ ] J'ai ajouté des tests qui couvrent le nouveau code

## Comment tester

En local / staging :
- Récupérer la base de production
- Aller sur http://localhost:8000
- Cliquer sur ABC
- …

## Développement local

- Mettre à jour le `.env`
- Réinstaller les dépendances Python avec `pip install -r requirements.txt -r dev-requirements.txt`
- Réinstaller les dépendances node avec `npm install`
- Rebuild la stack docker avec `docker compose build`
- ...

## Déploiement

- Exécuter les migrations
- Exécuter la commande `rf -rf /`
- ...

2024-09-03 06:29 UTC, kolok commented
Vu avec @fabienheureux 
2 pb ici

- [ ] le bouton «Rechercher dans cette zone» est affiché en permanance
- [ ] La carte est recentré sur les points lors de l'affichage de la carte détaillée de l'acteur : On perd le zoom, la punaise de l'acteur peut passé sous la légende.

Idéalement, on aimerait que la carte se recentre sur la punaise de l'acteur sans modifier le niveau de zoom lorsqu'on affiche sa carte détaillée

Note de réflexion : est-ce qu'on a pas quelque chose à faire avec un système de callback quand la carte est chargée entièrement o alors jouer avec le debounce du controlleur à la fin de l'initialisation ?

2024-09-03 09:32 UTC, fabienheureux commented
> Note de réflexion : est-ce qu'on a pas quelque chose à faire avec un système de callback quand la carte est chargée entièrement o alors jouer avec le debounce du controlleur à la fin de l'initialisation ?

En fait le soucis qu'on a ici c'est dans le cas du Loiret, même à la fin de l'initialisation, la carte étant _cachée_ dans un accordéon, le `fitBounds` ne va pas fonctionner.   
Dans les autres situations, si le soucis est un délai de _painting_ de la page ou de mise en place des éléments, on peut tomber bien, mais on peut quand même avoir des soucis. 
Exemple auquel je pense : du lazy loading d'images avec des width/height mal définies, ça peut faire bouger la mise en page et donc la taille de l'iframe et fausser le `fitBounds`

2024-09-04 14:25 UTC, fabienheureux commented on static/to_compile/src/solution_map.ts
> -        this.#map = L.map("map", {
Je me suis permis de supprimer ce préfixe qui normalement décrit une property privée. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties

2024-09-05 07:03 UTC, kolok requested changes
Malheureusement, on a toujours les 2 comportements problématique, à savoir :
2 pb ici

- le bouton «Rechercher dans cette zone» est affiché en permanance
- La carte est recentré sur les points lors de l'affichage de la carte détaillée de l'acteur : On perd le zoom, la punaise de l'acteur peut passer sous la légende.

2024-09-05 07:11 UTC, fabienheureux commented
Tu es sûr que tu as pas du cache navigateur ? Ou parcel ?
Normalement c'est corrigé justement

2024-09-05 08:09 UTC, kolok approved these changes
My bad !

ça marche très bien
Peut-être qu'on n'a pas besoin du dataset.mapResize

2024-09-05 09:40 UTC, merged