remove search button and trigger search
incubateur-ademe/quefairedemesobjets pull request #942
Opened 2024-10-16 16:09 UTC by fabienheureux

# Description succincte du problème résolu

Carte Notion : [Recherche adresse - Supprimer le bouton “rechercher” pour l’adresse au niveau de la carte](https://www.notion.so/accelerateur-transition-ecologique-ademe/Recherche-adresse-Supprimer-le-bouton-rechercher-pour-l-adresse-au-niveau-de-la-carte-1113cdef565643d186bc08148ef31dc4?pvs=4)

- Suppression du widget obsolète AutocompleteAndSearch
- Renommage dans une méthode pour faciliter la lecture 
- Modification du callback déclenché lorsqu'on sélectionne une option 

**Type de changement** :

- [ ] Bug fix
- [ ] Nouvelle fonctionnalité
- [ ] Mise à jour de données / DAG
- [ ] Les changements nécessitent une mise à jour de documentation
- [ ] Refactoring de code (explication à retrouver dans la description)

## Auto-review

Les trucs à faire avant de demander une review :

- [ ] J'ai bien relu mon code
- [ ] La CI passe bien
- [ ] En cas d'ajout de variable d'environnement, j'ai bien mis à jour le `.env.template`
- [ ] J'ai ajouté des tests qui couvrent le nouveau code

## Comment tester

En local / staging :
- …

2024-10-16 16:11 UTC, fabienheureux commented on jinja2/qfdmo/adresses.html
> -                           address-autocomplete:optionSelected->search-solution-form#checkAdresseErrorForm
on appelle déjà cette méthode dans `advancedSubmit` donc pas de risque :)

2024-10-17 07:10 UTC, fabienheureux commented on e2e_tests/search_update.spec.ts
> +    // await page.locator("button[data-testid=rechercher-adresses-submit]").click()
```suggestion
```

2024-10-17 07:10 UTC, fabienheureux commented on static/to_compile/entrypoints/qfdmo.ts
> +// stimulus.debug = true
j'ai rajouté ça commenté, plus simple pour quand on doit l'activer / désactiver

2024-10-17 08:22 UTC, kolok requested changes
Il y a une regression

En mode formulaire :
* chercher un produit
* chercher une adresse
* selectionner une adresse

-> la carte est direct affichée

On veut das ce cas que la carte ne soit affichée que quand l'utilisateur clique sur le bouton `Rechercher des adresses`

2024-10-17 08:27 UTC, kolok commented on e2e_tests/search_update.spec.ts
> -    await page.locator("button[data-testid=rechercher-adresses-submit]").click()
ici on veut garder le click car on est en mode formulaire

2024-10-17 08:27 UTC, kolok commented on jinja2/qfdmo/_addresses_partials/adresse_input_form.html
> +        <span class="qfdmo-italic qfdmo-text-sm">Taper et sélectionner une adresse ci-dessous pour lancer la recherche</span>
On ne veut pas afficher cette mention en mode formulaire

2024-10-17 08:27 UTC, kolok commented on jinja2/qfdmo/adresses.html
> -                           address-autocomplete:optionSelected->search-solution-form#checkAdresseErrorForm
Voir si ça n'a pas d'impact sur le mode formulaire -> ceppendant, je n'en ai pas vu

2024-10-17 21:11 UTC, kolok approved these changes

2024-10-18 11:08 UTC, merged